### ISSUE TITLE
nistats or nilearn

### ISSUE THREAD

**Issue by yibeichan** [nipype/pydra-fitlins#1]
hello @effigies , I'm working on converting interfaces to pydra. In fitlins, there is a `nistats.py` under `fitlins/fitlins/interfaces/`. Since `nistats` has become part of `nilearn`, would you prefer if I use `nilearn.py` instead of `nistats.py` in pydra?

**Comment by effigies** [comment]
> hello @effigies , I'm working on converting interfaces to pydra. In fitlins, there is a `nistats.py` under `fitlins/fitlins/interfaces/`. Since `nistats` has become part of `nilearn`, would you prefer if I use `nilearn.py` instead of `nistats.py` in pydra?

Sounds good to me.
